# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective : # Ganti dengan satu nama pengguna Open Collective
ko_fi : # Ganti dengan satu nama pengguna Ko-fis
tidelift     : # Ganti dengan satu Tidelift platform-name/package-name misalnyabj, npm
community_bridge   : # Ganti dengan nama proyek Community Bridge misalny, cloud-foun
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
